// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gmfqrzyvroklfhpbgzoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtZnFyenl2cm9rbGZocGJnem9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNzA2MTEsImV4cCI6MjA4Njk0NjYxMX0.z9ANqVAocD2Bzl9uhv0j4UWx2RsfqjDGn7Ys_f6iFfs";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);